In [ ]:
!pip install youtube-transcript-api
!pip install pytube3
!pip install pafy
!pip install youtube_dl
!pip install yt-dlp

Collecting youtube-transcript-api
  Downloading youtube_transcript_api-1.2.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: defusedxml<0.8.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from youtube-transcript-api) (0.7.1)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from youtube-transcript-api) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-transcript-api) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-transcript-api) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-transcript-api) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->youtube-transcript-api) (2026.4.22)
Downloading youtube_transcript_api-1.2.4-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.2/485.2 kB 9.4 MB/s eta 0:00:00
Installing collected packages: youtube-transcript-api
Successfully installed youtube-transcript-api-1.2.4
Collecting pytube3
  Downloading pytube3-9.6.4-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from pytube3) (4.15.0)
Downloading pytube3-9.6.4-py3-none-any.whl (38 kB)
Installing collected packages: pytube3
Successfully installed pytube3-9.6.4
Collecting pafy
  Downloading pafy-0.5.5-py2.py3-none-any.whl.metadata (10 kB)
Downloading pafy-0.5.5-py2.py3-none-any.whl (35 kB)
Installing collected packages: pafy
Successfully installed pafy-0.5.5
Collecting youtube_dl
  Downloading youtube_dl-2021.12.17-py2.py3-none-any.whl.metadata (1.5 kB)
Downloading youtube_dl-2021.12.17-py2.py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 31.7 MB/s eta 0:00:00
Installing collected packages: youtube_dl
Successfully installed youtube_dl-2021.12.17
Collecting yt-dlp
  Downloading yt_dlp-2026.3.17-py3-none-any.whl.metadata (182 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.3/182.3 kB 5.7 MB/s eta 0:00:00
Downloading yt_dlp-2026.3.17-py3-none-any.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 66.4 MB/s eta 0:00:00
Installing collected packages: yt-dlp
Successfully installed yt-dlp-2026.3.17

In [ ]:
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api.formatters import TextFormatter
import yt_dlp

In [ ]:
def get_video_urls(playlist_url):
    ydl_opts = {
        'quiet': True,
        'extract_flat': True,  # Only extract URLs
    }

    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        playlist_info = ydl.extract_info(playlist_url, download=False)
        video_urls = [entry['url'] for entry in playlist_info['entries']]
        video_titles = [entry['title'] for entry in playlist_info['entries']]
        return video_urls, video_titles

In [ ]:

def getTranscript(playlist_url):
  video_urls, video_titles = get_video_urls(playlist_url)

  SPEECH_DICT = {}
  for i in range(0,len(video_urls)):
    url = video_urls[i]
    title = video_titles[i]
    print(title)

    # get video id
    video_id = url.split('https://www.youtube.com/watch?v=')[1]

    SPEECH_DICT[video_id] = {}
    SPEECH_DICT[video_id]['url'] = url
    SPEECH_DICT[video_id]['title'] = title
    try:
      # get all the list of transcripts available in diff languages
      transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

      # find the one which is in hindi
      transcript = transcript_list.find_transcript(['hi'])

      # translate the transcript to english
      translated_transcript = transcript.translate('en')
      eng_transcript = translated_transcript.fetch()

      # format the transcript to sentence string
      formatter = TextFormatter()
      formatted_transcript = formatter.format_transcript(eng_transcript).replace('\n',' ').replace('[appreciation]','').replace('[music]','')

      # append in the list of speeches
      SPEECH_DICT[video_id]['text'] = formatted_transcript
    except:
      try:
        # get all the list of transcripts available in diff languages
        transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)

        # find the one which is in hindi
        transcript = transcript_list.find_transcript(['en'])

        # translate the transcript to english
        translated_transcript = transcript.translate('en')
        eng_transcript = translated_transcript.fetch()

        # format the transcript to sentence string
        formatter = TextFormatter()
        formatted_transcript = formatter.format_transcript(eng_transcript).replace('\n',' ').replace('[appreciation]','').replace('[music]','')

      # append in the list of speeches
        SPEECH_DICT[video_id]['text'] = formatted_transcript
      except:
        SPEECH_DICT[video_id]['text'] = 'No Transcript Available'

  return SPEECH_DICT

In [ ]:
playlist_urls = ["https://www.youtube.com/playlist?list=PLqtVCj5iilH4Ia-QrpzLPmU-I2kkKbMql",
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH7VO-yhOJk08TDHVenjvEQ3",#independence day speeches
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH7FPEj8iWVe2ZW-ADtOkwjK",#atal bihari vajpayee
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH5vp001YjQNIn7AgmHqwAnx",#apj abdul kalam
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH6EtIep58nXOf84EFXGw7fi",#ram nath kovid
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH5NtsLtRYjjASsY92n9qdp0",#pratibha patil
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH7qQM0desSK3HmwEcUDhuO0",#radha krishana
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH58HBRYbZYlXdRFU4uejG4m",#neelam sanjeeva reddy
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH4QghSrtPnTrdgoGZyhcM22",#president speeches
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH6vh2rG-PcuQe_F2OiEyw8F",#morarji desai
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH4r0InJt9XYTrEWRGU0ccG6",#lal bahadur shastri
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH4yNuJ0c7paHwzh6HZG5ooV",#indira gandhi
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH4SkGxWM7k8X6N1F3jZyh-Q",#jawaharlal nehru
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH60r9bvyWNbq5QFcF1z9Xs8",#election speeches
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH4vmSDciJZhSRl2oTEJvGMi",#rajiv gandhi
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH4_cmJ9CzdfWD5tCRMWMbml",#pranab mukherjee
                 "https://www.youtube.com/playlist?list=PLqtVCj5iilH6Zfa_OPKixsq7e__wxJTLj",#kr narayan
                 ]

In [ ]:
import six
import pandas as pd

dfs = []
for playlist_url in playlist_urls:
  speech_dict = getTranscript(playlist_url)
  urls = []
  titles = []
  text = []
  for key,val in six.iteritems(speech_dict):
    urls.append(val['url'])
    titles.append(val['title'])
    text.append(val['text'])
  df = pd.DataFrame({'url':urls,'title':titles,'text':text})
  dfs.append(df)

WARNING: [youtube:tab] YouTube said: INFO - 4 unavailable videos are hidden

1977 - Morarji Desai Speech | Janta Party Rally
1977 - Atal Bihari Vajpayee Speech | Janta Party Rally
1977 - Then Janta Party President Chandrashekhar speaking in a Rally
1977 - Atal Bihari Vajpayee victory rally Speech | Janta Party Rally
1977 - Babu Jagjiwan Ram Speech | Janta Party Rally
[Private video]
1995 - Jaswant Singh in an election debate on Doordarshan
1988 By-elections | A Discussion
1989- Former Prime Minister I K Gujral in an election discussion on Doordarshan
1995 - Former PM Atal Bihari Vajpayee in an election debate on Doordarshan
1995 - Ram Vilas Paswan in an election debate on Doordarshan
1989 - Anand Sharma talking about booth capturing | General Election
1989 - P.V Narasimha Rao talking about stable government | General Election
1989 - Jaswant Singh talking about booth capturing | General Election
1989 - Harkishan Singh Surjeet talking about booth capturing | General Election
1989 - Yashwant Sinha talking about booth capturing | General Election
1997 -  Inter-parliamentary Specialized Conference
1997 - Farewell by MPs to then President Dr  Shankar Dayal Sharma
2013 - Shivshankar Menon's Speech on India & The World
2014 - Dr Chandan Mitra delivers Sardar Patel Memorial Lecture on Socialism & Integral Humanism
1971 - Indira Gandhi's Broadcast to the Nation | Indo-Pakistan War
1965 - Then PM Lal Bahadur Shastri's speech on Spirit of World religion | विश्वधर्म भावना और स्वरूप
1965 - Then PM Lal Bahadur Shastri's speech on Life Philosophy & Welfare | जीवन दर्शन और विश्वकल्याण
1965 - Then PM Lal Bahadur Shastri's speech on Religion & World Peace | धर्म विज्ञान और विश्व शांति
1972 - Sheikh Mujibur Rahman's Public Address in Dhaka
1959 - Martin Luther King Jr.'s Speech on The Spirit of Mahatma Gandhi
1996 - Atal Bihari Vajpayee's speech on General Elections results
Lal Bahadur Shashtri | Jai Jawan Jai Kisan
2002 - Then PM Atal Bihari Vajpayee's speech during his visit to Kashmir
1977 - Then Foreign Minister Atal Bihari Vajpayee as 1st Indian leader to address UNGA in Hindi
July 1991 - Then PM P. V. Narasimha Rao's Broadcast to the Nation
June 1991 - Then PM P. V. Narasimha Rao's Message to the Nation
1993 - Then President Dr. Shankar Dayal Sharma’s Address to the both Houses of Parliament
1991 - Then Prime Minister P. V. Narasimha Rao on Indian Economy
1946 - Constituent Assembley Debates
1947 - Muhammad Ali Jinnah's Speech in Pakistan's Constituent Assembly | Karachi
1947 - Muhammad Ali Jinnah's Broadcast on Radio
1962 - Pt. Jawahar Lal Nehru Speech in Lok Sabha | (20.11.1962)
1999 में कारगिल युद्ध पर तत्कालीन  प्रधानमंत्री अटल बिहारी वाजपेयी
[Private video]
[Private video]
[Private video]
1990 - Then PM V.P. Singh on Ram Mandir on Independence Day | Red Forts
1977 - Then PM Morarji Desai on India as a Strong Nation | Red Fort
1979 - Then PM Chaudhary Charan Singh on Farmers | Red Fort
1947 - Excerpts from Constituent Assembly Speeches
1977 - Atal Bihari Vajpayee on Emergence of Janata Party
1997 - तत्कालीन प्रधानमंत्री इन्द्र कुमार गुजराल सब्सिडी पर बात करते हुए
1967 - Pt. Deen Dayal Upadhyay on Subhash Chandra Bose | Red Fort
1961 - Pt. Deen Dayal Upadhyay Speech on Demise of Pt. Govind Ballabh Pant
2002 - अंतकवाद पर पाकिस्तान का दोहरा चरित्र - Atal Bihari Vajpayee
2000 - Then USA President Bill Clinton Address To Parliament
2002 - Then PM Atal Bihari Vajpayee speech in Parliament on POTA
1962 - Pt. Jawaharlal Nehru Broadcast To The Nation on Chinese Aggression
1990 - Then Dy. Prime Minister L.K. Advani on Kashmir & Dr. Syama Prasad Mukherjee
1938 - C. Rajagopalachari (CM Madras) Message At The Inauguration of Akashvani Chennai

WARNING: [youtube:tab] YouTube said: INFO - 1 unavailable video is hidden

India's 76th  Independence Day Celebrations – PM’s address to the Nation - LIVE from the Red Fort.
2014 - PM Narendra Modi on Planning Commission | Red Fort
[Private video]
1998 - Then PM Atal Bihari Vajpayee's Independence Day Speech | Part 2
1998 - Then PM Atal Bihari Vajpayee's Independence Day Speech | Part 1
1979 - Then PM Chaudhary Charan Singh From the ramparts of the Red Fort
2020 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2019 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2018 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2017 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2016 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2015 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2013 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2011 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2010 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2009 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2008 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2007 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2006 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
2004 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
2002 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
1998 - Then PM Atal Bihari Vajpayee's Independence Day Speech
1994 - Then PM P. V. Narasimha Rao's Independence Day Speech
1993 - Then PM P. V. Narasimha Rao's Independence Day Speech
1988 - Then PM Rajiv Gandhi's Independence Day Speech
1986 - Then PM Rajiv Gandhi's Independence Day Speech
1978 - Then PM Morarji Desai's Independence Day Speech
1965 - Then PM Lal Bahadure Shastri's Independence Day Speech
1963 - Then PM Pandit Jawaharlal Nehru's Independence Day Speech
1950 - Then PM Pandit Jawaharlal Nehru's Independence Day Speech
1948 - Then PM Pandit Jawaharlal Nehru's Independence Day Speech
1947 - Then PM Pandit Jawaharlal Nehru's Independence Day Speech
India's 74th  Independence Day Celebrations – PM’s address to the Nation - LIVE from the Red Fort.
73rd Independence Day Celebrations – PM’s address to the Nation - LIVE from the Red Fort
72nd Independence Day Celebrations – PM’s address to the Nation - LIVE from the Red Fort
2017 - PM Narendra Modi's Independence day speech
2016 - PM Narendra Modi's Independence day speech
2015 - PM Narendra Modi's Independence day speech
2014 - PM Narendra Modi's Independence day speech
67th Independence Day Celebrations – PM’s address to the Nation - LIVE from the Red Fort
2012 - Then PM Manmohan Singh's Independence day speech
2011 - Then PM Manmohan Singh's Independence day speech
2010 - Then PM Manmohan Singh's Independence day speech
2009 - Then PM Manmohan Singh's Independence day speech
2008 - Then PM Manmohan Singh's Independence day speech
2007 - Then PM Manmohan Singh's Independence day speech
2006 - Then PM Manmohan Singh's Independence day speech
1947 - Then PM Jawaharlal Nehru's Independence Day Speech at midnight | Tryst with Destiny
1973 - Then PM Indira Gandhi's Independence Day Speech
1972 - Then PM Indira Gandhi's Independence Day Speech
1975 - Then PM Indira Gandhi's Independence Day Speech
1980 - Then PM Indira Gandhi's Independence Day Speech
1968 - Then PM Indira Gandhi's Independence Day Speech
1970 - Then PM Indira Gandhi's Independence Day Speech
1967 - Then PM Indira Gandhi's Independence Day Speech
1966 - Then PM Indira Gandhi's Independence Day Speech
1971 - Then PM Indira Gandhi's Independence Day Speech
1981 - Then PM Indira Gandhi's Independence Day Speech
1979 - Then PM Chaudhary Charan Singh's Independence Day Speech
1977 - Then PM Morarji Desai's Independence Day Speech
1964 - Then PM Lal Bahadur Shastri's Independence Day Speech
1962 - Then PM Jawaharlal Nehru's Independence Day Speech
1961 - Then PM Jawaharlal Nehru's Independence Day Speech
Independence Day Speeches of PMs | Promo
1960 - Then PM Jawaharlal Nehru's Independence Day Speech
1959 - Then PM Jawaharlal Nehru's Independence Day Speech
1958 - Then PM Jawaharlal Nehru's Independence Day Speech
1957 - Then PM Jawaharlal Nehru's Independence Day Speech
1956 - Then PM Jawaharlal Nehru's Independence Day Speech
1955 - Then PM Jawaharlal Nehru's Independence Day Speech
1954 - Then PM Jawaharlal Nehru's Independence Day Speech
1953 - Then PM Jawaharlal Nehru's Independence Day Speech
1952 - Then PM Jawaharlal Nehru's Independence Day Speech
1951 - Then PM Jawaharlal Nehru's Independence Day Speech
1949 - Then PM Jawaharlal Nehru's Independence Day Speech
1949 - Then Deputy PM Sardar Patel's Independence Day Message
1948 - Then Deputy PM Sardar Patel's Broadcast to Nation
1984 - Then PM Indira Gandhi's Independence day speech
2005 - Then PM Manmohan Singh's Independence day speech
2004 - Then PM Manmohan Singh's Independence day speech
1995 - Then PM PV Narasimha Rao's Independence Day Speech
2003 - Then PM Atal Bihari Vajpayee's Independence Day Speech
2002 - Then PM Atal Bihari Vajpayee's Independence Day Speech
1989 - Then PM Rajiv Gandhi's independence day speech
2001 - Then PM Atal Bihari Vajpayee's independence day speech
2000 - Then PM Atal Bihari Vajpayee's independence day speech
1976 - Emergency era Independence Day Speech of Indira Gandhi
1987 - Then PM Rajiv Gandhi's Independence Day Speech
1992 - Then PM PV Narasimha Rao's independence day speech
1999 - Then PM Atal Bihari Vajpayee's Independence Day speech
1996 - Then PM HD Deve Gowda's Independence Day speech | Freedom’ for Every Indian
1985 - Then PM Rajiv Gandhi's Independence Day speech | Call for National “Harmony”
1991: When Former PM PV Narasimha Rao Asked a Nation to ‘Believe’ Again
1997 - 50 years of freedom: Former PM IK Gujral’s Message to The Nation That Still Resonates Today
1990 - Former PM V.P. Singh’s Words That Lit A Flame of Courage Across Nation
From the Ramparts of Red Fort in 1983: Indira Gandhi’s voice that moved a nation
1982 - Then PM Indira Gandhi's Independence Day Speech

WARNING: [youtube:tab] YouTube said: INFO - 1 unavailable video is hidden

2002 - Atal Bihari Vajpayee's Address to the 57th UN General Assembly
1977 - Then Foreign Minister Atal Bihari Vajpayee as 1st Indian leader to address UNGA in Hindi
1999 में कारगिल युद्ध पर तत्कालीन  प्रधानमंत्री अटल बिहारी वाजपेयी
1998 - Atal Bihari Vajpayee - "Jai Jawan - Jai Kisan - Jai Vigyan" | Red Fort
1977 - Atal Bihari Vajpayee on Emergence of Janata Party
1977 - Atal Bihari Vajpayee address the nation..."राष्ट्रीय जाग्रयम् वयम्"
Atal Bihari Vajpayee speech at Amritsar karyakarta sammelan
Post Kargil victory, Atal Bihari Vajpayee addresses a rally in Chandigarh
After beating Pakistan in Kargil war, Atal Bihari Vajpayee addresses rally in Chennai
2003 Rajasthan Elections - Atal Bihari Vajpayee addresses a rally in Jaipur
2003 Rajasthan Polls - Atal Bihari Vajpayee addresses a rally in Ajmer
2003 Rajasthan Polls - Atal Bihari Vajpayee addresses a rally in Jodhpur
2003 - Then PM Atal Bihari Vajpayee's Independence Day Speech
2002 - Then PM Atal Bihari Vajpayee's Independence Day Speech
2001 - Then PM Atal Bihari Vajpayee's independence day speech
2000 - Then PM Atal Bihari Vajpayee's independence day speech
1999 - Then PM Atal Bihari Vajpayee's Independence Day speech
1999 Elections - Atal Bihari Vajpayee's rally after beating Pakistan in Kargil War
1999 General Elections - Atal Bihari Vajpayee addresses a Rally in Haryana
1998 General Elections - Atal Bihari Vajpayee adresses a rally in Sikar, Rajasthan
1998 General Elections - Atal Bihari Vajpayee addresses a rally in Jabalpur
1998 Rajasthan Assembly Elections - Atal Bihari Vajpayee's rally in Kota
1998 General Elections - Atal Bihari Vajpayee's Rally at Khargaon in Madhya Pradesh
1998 General elections - Atal Bihari Vajpayee's Election rally in Bastar
1998 Rajasthan Assembly Election | Atal Bihari Vajpayee Speech in Bharatpur
Sh. Atal Bihari Vajpayee - Rajendra Prasad Memorial Lecture (29.11.1992) Part-2
Sh. Atal Bihari Vajpayee - Rajendra Prasad Memorial Lecture (28.11.1992) Part-1
1984 - General Election Broadcast by Atal Bihari Vajpayee
1977 General Elections | Janata Party victory rally in Delhi | Atal Bihari Vajpayee Speech
1977 - Atal Bihari Vajpayee Speech | Janta Party Rally
1995 - Former PM Atal Bihari Vajpayee in an election debate on Doordarshan
1977 - Atal Bihari Vajpayee victory rally Speech | Janta Party Rally
1997 - Atal Bihari Vajpayee's Speech on Netaji Subhas Chandra Bose
Anugoonj । Episode-36 । Atal Bihari Vajpayee । Politics
1996 - Atal Bihari Vajpayee's speech on General Elections results
1971 - Jan Sangh MP Vajpayee's support to Cong Govt in Parliament for Pak war
1998 - Then PM Atal Bihari Vajpayee's Independence Day Speech
2002 - Then PM Atal Bihari Vajpayee's speech during his visit to Kashmir
Atal Bihari Vajpayee | Former Prime Minister | Lokpriya | Sangrahalay Ke Galiyaron Se
Then PM Atal Bihari Vajpayee unveiling statue of Hemu Kalani | Freedom Fighter
Atal Bihari Vajpayee unveiling statue of Maharaja Ranjit Singh |  Sher-e-Punjab
2002 - Then PM Atal Bihari Vajpayee & Russian President Vladimir Putin signed MoU
2002 - Then PM Atal Bihari Vajpayee Inaugurated Delhi Metro's First-Ever Corridor
1998 - Then PM Atal Bihari Vajpayee's Independence Day Speech | Part 1
1998 - Then PM Atal Bihari Vajpayee's Independence Day Speech | Part 2
2003 - 3rd SAARC Information Ministers' Conference by PM Atal Bihari Vajpyaee
2002 - अंतकवाद पर पाकिस्तान का दोहरा चरित्र - Atal Bihari Vajpayee
2000 - Then Prime Minister Atal Bihari Vajpayee on Good Health | Seminar
[Private video]
2002 - Then PM Atal Bihari Vajpayee speech in Parliament on POTA
मैं अटल हूँ | Atal Bihari Vajpayee | A Poet in Words, A Statesman in Action
ATAL | A Poet’s Heart, Courage in Action, A Statesman’a Spine
Dr. A.P.J. Abdul Kalam | Missile Man | Documentary
2006 - A. P. J. Abdul Kalam Addressing the  Budget Session
2003 - Dr A. P. J. Abdul Kalam Addressing the Budget Session
2005 - Dr A. P. J. Abdul Kalam Addressing the Budget Session
2002 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
2004 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
2006 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
Dr A. P. J. Abdul Kalam - A Universal Personality
2017 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2018 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2019 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2020 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2007 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2008 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2009 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2010 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2011 - Pratibha Patil's Message to the Nation | Eve of Independence Day
1962 - Dr. Sarvepalli Radhakrishnan's Message to the Nation | Eve of Independence Day
1963 - Dr. Sarvepalli Radhakrishnan's message to the nation on the eve of Independence Day
1964 - Dr. Sarvepalli Radhakrishnan Message to the Nation | Eve of Independence Day
1965 - Dr. Sarvepalli Radhakrishnan's Message to the Nation | Eve of Independence Day
Dr Sarvepalli Radhakrishnan | Life & Work | Documentary
Dr. S. Radhakrishnan's Speech in Constituent Assembly
Dr. Sarvapalli Radhakrishnan | Teachers Day | Birth Anniversary
1977 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1978 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1979 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1980 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1947 - Dr. Rajendra Prasad's Message to the Nation | Eve of 1st Independence Day
1951 - Dr. Rajendra Prasad's Message to the Nation | Eve of Independence Day
1952 - Dr. Rajendra Prasad's Message to the Nation on the eve of Independence Day
1962 - Dr. Sarvepalli Radhakrishnan's Message to the Nation | Eve of Independence Day
1963 - Dr. Sarvepalli Radhakrishnan's message to the nation on the eve of Independence Day
1964 - Dr. Sarvepalli Radhakrishnan Message to the Nation | Eve of Independence Day
1965 - Dr. Sarvepalli Radhakrishnan's Message to the Nation | Eve of Independence Day
1968 - V V Giri's Message to the Nation | Eve of Independence Day
1970 - V V Giri's Message to the Nation | Eve of Independence Day
1974 - V V Giri's Message to the Nation | Eve of Independence Day
1976 - Fakhruddin Ali Ahmed's Message to the Nation | Eve of Independence Day
1977 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1978 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1979 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1980 - Neelam Sanjiva Reddy's Message to the Nation | Eve of Independence Day
1982 - Gyani Zail Singh" s message to Nation | Eve of Independence Day
1983 - Gyani Zail Singh's Message to Nation | Eve of Independence Day President Speech
1984 - Gyani Zail Singh's Message to Nation | Eve of Independence Day
1985 - Gyani Zail Singh's Message to Nation | Eve of Independence Day
1986 - Gyani Zail Singh's Message to Nation | Eve of Independence Day
1987 - R. Venkataraman's Message to the Nation | Eve of Independence Day
1988 - R. Venkataraman's Message to the Nation | Eve of Independence Day
1989 - R. Venkataraman's Message to the Nation | Eve of Independence Day
1990 - R Venkataraman' s Message to the Nation | Eve of Independence Day
1991 - R Venkataraman' s Message to the Nation | Eve of Independence Day
1992 - Dr Shankar Dayal Sharma's Message to the Nation | Eve of Independence Day
1993 - Dr Shankar Dayal Sharma's Message to the Nation | Eve of Independence Day
1994 - Dr Shankar Dayal Sharma's Message to the Nation | Eve of Independence Day
1995 - Dr Shankar Dayal Sharma's Message to the Nation | Eve of Independence Day
1996 - Dr. Shankar Dayal Sharma' s Message to the Nation | Eve of Independence Day
1999 - K. R. Narayanan' s Message to the Nation | Eve of Independence Day
2002 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
2004 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
2006 - A. P. J. Abdul Kalam's Message to the Nation | Eve of Independence Day
2007 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2008 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2009 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2010 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2011 - Pratibha Patil's Message to the Nation | Eve of Independence Day
2013 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2015 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2016 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2017 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2018 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2019 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
2020 - Ram Nath Kovind's Message to the Nation | Eve of Independence Day
1977 - Then PM Morarji Desai on India as a Strong Nation | Red Fort
1977 - Then Prime Minister Morarji Desai's visit to USSR (Russia)
1978 - Then Prime Minister Morarji Desai On Return from U.S. Visit
1978 - Then PM Morarji Desai's Independence Day Speech
1977 - Morarji Desai Speech | Janta Party Rally
1963 - Morarji Desai speech on Indian unity | Part 2 | Sardar Patel Memorial Lecture
1963 - Morarji Desai speech on Indian unity | Part 1 | Sardar Patel Memorial Lecture
1977 general elections - Speeches of Janata Party leaders after their victory
1977 general elections - Speeches of Janata Party leaders after their victory
Post-Emergency, Morarji Desai addresses rally in Guwahati
Morarji Desai addresses a rally in Saharanpur after Emergency
Breaking Chains of Fear | In 1977 Desai’s call to protect the DEMOCRACY
1977 - Then PM Morarji Desai's Independence Day Speech
Documentary on Former PM Morarji Desai's political journey
Lal Bahadur Shastri | National Unity | Hero of Independence
Lal Bahadur Shastri - Former Prime Minister | धरती का लाल | Ep. 9
Lal Bahadur Shastri - Former Prime Minister | धरती का लाल | Ep. 8
Lal Bahadur Shastri - Former Prime Minister | धरती का लाल | Ep. 5
Lal Bahadur Shastri - Former Prime Minister | धरती का लाल | Ep. 4
Lal Bahadur Shastri - Former Prime Minister | धरती का लाल | Ep. 3
Lal Bahadur Shastri - Former Prime Minister | धरती का लाल | Ep. 2
Lal Bahadur Shastri - Former Prime Minister | धरती का लाल | Ep. 1
The slogans of Lal Bahadur Shastri ji | "Jai Jawan - Jai Kisan"
Three Slogans of Lal Bahadur Shastri ji | "Jai Jawan - Jai Kisan - Jai Hind"
Lal Bahadur Shastri | Poem by Ramanath Awasthi
Lal Bahadur Shashtri | Jai Jawan Jai Kisan
1965 - Then PM Lal Bahadure Shastri's Independence Day Speech
Lal Bahadur Shastri | Former Prime Minister | Lokpriya | Sangrahalaya Ke Galiyaron Se
1993 - Inauguration of Mahatma Gandhi's statue & Lal Bahadur Shastri's photo in Parliament
1965 - Then PM Lal Bahadur Shastri's speech on Raajdharma Aur Raajkarma | राजधर्म और राजकर्मा
1965 - Then PM Lal Bahadur Shastri's speech on Religion & World Peace | धर्म विज्ञान और विश्व शांति
1965 - Then PM Lal Bahadur Shastri's speech on Life Philosophy & Welfare | जीवन दर्शन और विश्वकल्याण
1965 - Then PM Lal Bahadur Shastri's speech on Spirit of World religion | विश्वधर्म भावना और स्वरूप
Lal Bahadur Shastri | 2nd Prime Minister of India
Hamari Yadon Mein Lal Bahadur Shasti ji | लाल बहादुर शास्त्री
Lal Bahadur Shastri | Documentary | Birth Anniversary
1964 - Then PM Lal Bahadur Shastri's Independence Day Speech
1965 Indo-Pak war - Lal Bahadur Shastri addressess the nation
Lal Bahadur Shastri gives the slogan of 'Jai Jawan, Jai Kisan'

WARNING: [youtube:tab] YouTube said: INFO - 5 unavailable videos are hidden

1982 - Then PM Indira Gandhi's visit to USA
Indira Gandhi's visit to Lakshadweep
Indira Gandhi's 20 point program - Special Address to Nation
Indira Gandhi at Deoband - centenary celebrations of Darul Uloom
Visit to Shanti Niketan - circa 1980s
Gandhi Jayanti at Canberra Australia 1981
1981 - UK PM Margaret Thatcher's visit to India
Kasturba Gram Aur Bharat Bhawan   A Report from 1980s
From the Ramparts of Red Fort in 1983: Indira Gandhi’s voice that moved a nation
1982 - Then PM Indira Gandhi's Independence Day Speech
1984 - Then PM Indira Gandhi's Independence day speech
1971 - Then PM Indira Gandhi's Independence Day Speech
1966 - Then PM Indira Gandhi's Independence Day Speech
1970 - Then PM Indira Gandhi's Independence Day Speech
1968 - Then PM Indira Gandhi's Independence Day Speech
1967 - Then PM Indira Gandhi's Independence Day Speech
1975 - Then PM Indira Gandhi's Independence Day Speech
1980 - Then PM Indira Gandhi's Independence Day Speech
1981 - Then PM Indira Gandhi's Independence Day Speech
1972 - Then PM Indira Gandhi's Independence Day Speech
1973 - Then PM Indira Gandhi's Independence Day Speech
[Private video]
1972 - Indira Gandhi's Address at Parade Ground | New Delhi
Smt. Indira Gandhi's Public Address at Brigade Parade Ground, Kolkata
[Private video]
1971 - Indira Gandhi's Broadcast to the Nation | Indo-Pakistan War
1976 - Emergency era Independence Day Speech of Indira Gandhi
Indira Gandhi Public Meeting Election Speech, Ramanagara Karnataka 1982
Indira Gandhi on why she was expelled from the Parliament
1982 Elections - Indira Gandhi calls for stable government
1982 Elections - When Indira Gandhi promised Garibi Hatao
1982 Polls - Indira Gandhi in Hyderabad
Indira Gandhi in 1982 defends Emergency era decries khichdi sarkaar
1977 Elections - Indira Gandhi on Emergency
1983 - Indira Gandhi talks about defeat in post-Emergency Polls
1982 Elections - Indira Gandhi alleges Opposition trying to weaken India
1982 Andhra Elections - Then PM Indira Gandhi promises to eradicate poverty
1967 Election Rally - Indira Gandhi speaks on Gau Hatya
1982 - Then PM Indira Gandhi promises Garibi Hatao
1983 Assam Assembly Polls - Indira Gandhi talks about vote bank politics
Indira Gandhi after Emergency addresses a rally in Sivakasi
Post-Emergency Indira Gandhi election rally in Andhra Pradesh
Indira Gandhi after Emergency addresses a rally in Assam
[Private video]
1971 - Liberation of Bangladesh | Indira Gandhi's Broadcast to the Nation on 3.12.1971
1971 - Liberation of Bangladesh | Indira Gandhi & Sheikh Mujibur Rahman Public Address at Kolkata
1971 - Liberation of Bangladesh | Ft. V.V. Giri, Smt. Indira Gandhi & Sheikh Mujibur Rahman
1971- Liberation of Bangladesh | Pakistan Attacks | Indira Gandhi's Lok Sabha Statement on 4.12.1971
1971 - Liberation of Bangladesh | Indira Gandhi Interacting with the Media on 18.05.1971
1971 - Liberation of Bangladesh |  Rally in Support of Bangladesh in Delhi by Smt. Indira Gandhi
1971 - Liberation of Bangladesh | India Recognizes Bangladesh | Indira Gandhi Statement in Lok Sabha
1971 - Liberation of Bangladesh |  Indira Gandhi's Address to the Armed Forces
1971 - Liberation of Bangladesh | Public Speech of Indira Gandhi in Delhi on 12.12.1971
1971 - Liberation of Bangladesh | Surrender of Pakistani Forces in Bangladesh | 16.12.1971
1971 - Liberation of Bangladesh | Interview of Indira Gandhi Broadcast on NBC | 27.12.1971
1971 - Liberation of Bangladesh |  Public Meeting at Parade Ground, New Delhi | 10.01.1972
Indira Gandhi - An outspoken personality
1971 - Then PM Indira Gandhi's visit to Kremlin
1984 - Indira Gandhi speaks to Rakesh Sharma | Squadron Leader | First Indian to Space
[Private video]
[Private video]
1984 - Indira Gandhi speaks to Rakesh Sharma | Squadron Leader | First Indian to Space
1975 - Declaration of Emergency by Then PM Indira Gandhi
1975 - Then PM Indira Gandhi's Broadcast To The Nation

WARNING: [youtube:tab] YouTube said: INFO - 1 unavailable video is hidden

Jawaharlal Nehru's last TV Interview - May 1964
1951 - Then PM Jawaharlal Nehru's Independence Day Speech
1952 - Then PM Jawaharlal Nehru's Independence Day Speech
1953 - Then PM Jawaharlal Nehru's Independence Day Speech
Jawaharlal Nehru's interview with Arnold Michaelis - 1958
1954 - Then PM Jawaharlal Nehru's Independence Day Speech
1955 - Then PM Jawaharlal Nehru's Independence Day Speech
1956 - Then PM Jawaharlal Nehru's Independence Day Speech
1957 - Then PM Jawaharlal Nehru's Independence Day Speech
1958 - Then PM Jawaharlal Nehru's Independence Day Speech
1959 - Then PM Jawaharlal Nehru's Independence Day Speech
1960 - Then PM Jawaharlal Nehru's Independence Day Speech
1961 - Then PM Jawaharlal Nehru's Independence Day Speech
1962 - Then PM Jawaharlal Nehru's Independence Day Speech
1947 - Then PM Jawaharlal Nehru's Independence Day Speech at midnight | Tryst with Destiny
Jawaharlal Nehru celebrating his birthday with children
1947 - Jawaharlal Nehru's Constituent Assembly Speech Moving the Motion on Aug 15
1947 - Pt. Jawaharlal Nehru's Constituent Assembly Speech | Tryst with Destiny in Hindi
1947 - Jawaharlal Nehru's Constituent Assembly Speech on Aug 15
1949 - Then PM Jawaharlal Nehru's Independence Day Speech
1950 - Pt Jawahar Lal Nehru's Constituent Assembly Speech, Delhi
Jawahar Lal Nehru's Broadcast to the Nation ahead of 1951 General Elections
1946 - Pt. Jawahar Lal Nehru's Constituent Assembly speech at Delhi
1952 General Elections - Jawahar Lal Nehru's rally in Guwahati
1947 - Jawaharlal Nehru takes oath as Prime Minister
1948 - Then PM Pandit Jawaharlal Nehru's Independence Day Speech
1950 - Then PM Pandit Jawaharlal Nehru's Independence Day Speech
1963 - Then PM Pandit Jawaharlal Nehru's Independence Day Speech
[Private video]
1962 - Pt. Jawahar Lal Nehru Speech in Lok Sabha | (20.11.1962)
1947 - Pt. Jawaharlal Nehru's Constituent Assembly Speech | Tryst with Destiny (English)
Tribute To Mahatma Gandhi by Jawaharlal Nehru - 'The Light Has Gone Out of Our Lives'
1962 - Pt. Jawaharlal Nehru Broadcast To The Nation on Chinese Aggression
1964 - पंडित जवाहर लाल नेहरू की पुष्प कलश यात्रा का शिव कुमार त्रिपाठी द्वारा हिंदी में वृतांत

WARNING: [youtube:tab] YouTube said: INFO - 1 unavailable video is hidden

Documentary on Former PM Morarji Desai's political journey
1998 Rajasthan Assembly Election | Atal Bihari Vajpayee Speech in Bharatpur
1998 General elections - Atal Bihari Vajpayee's Election rally in Bastar
Jawahar Lal Nehru's Broadcast to the Nation ahead of 1951 General Elections
1998 Rajasthan Assembly Election | Atal Bihari Vajpayee Speech in Bharatpur
Documentary on Former PM Morarji Desai's political journey
1952 General Elections - Jawahar Lal Nehru's rally in Guwahati
1984 General Election Broadcast by PV Narsimha Rao
1984 - General Election Broadcast by Atal Bihari Vajpayee
1984 General Election Broadcast by Chaudhary Charan Singh
1977 General Elections - Congress rally at Shajapur in Madhya Pradesh
1998 General Elections - Atal Bihari Vajpayee addresses a rally in Jabalpur
1996 General Elections - Congress rally in Jalandhar
1993 Assembly Elections - Congress rally in Lucknow
1996 General Elections - HD Deve Gowda addresses rally in Varanasi
1999 General Elections - Atal Bihari Vajpayee addresses a Rally in Haryana
Post-Emergency Indira Gandhi election rally in Andhra Pradesh
1993 Mizoram Assembly Elections - Congress rally in Aizwal
1991 General Elections - Chandra Shekhar addresses a rally in Barabanki
1996 General Elections - HD Deve Gowda rally in Fatehpur
Breaking Chains of Fear | In 1977 Desai’s call to protect the DEMOCRACY
1998 General Elections - Congress rally in Nagpur
1998 General Elections - Atal Bihari Vajpayee adresses a rally in Sikar, Rajasthan
1997 Punjab Assembly Elections - HD Deve Gowda addresses a rally in Jalandhar
Indira Gandhi after Emergency addresses a rally in Assam
1998 General Elections - Congress rally in Jalandhar
1991 General Elections - Chandra Shekhar addresses a rally in Haryana
Post Kargil victory, Atal Bihari Vajpayee addresses a rally in Chandigarh
Morarji Desai addresses a rally in Saharanpur after Emergency
1984 General Elections - Congress rally in Varanasi
Post-Emergency, Morarji Desai addresses rally in Guwahati
2006 Assam Assembly elections - Congress rally in Guwahati
1993 Mizoram Assembly elections - Congress rally in Aizwal
After beating Pakistan in Kargil war, Atal Bihari Vajpayee addresses rally in Chennai
Rajiv Gandhi's election rally a day after Bhopal Gas Tragedy
After Bhopal Gas Tragedy, Rajiv Gandhi's election rally in Bengaluru
Rajiv Gandhi talks about Army's action in Punjab in 1984 Election rally
1996 General Elections - HD Deve Gowda addresses election rally in Lucknow
Indira Gandhi after Emergency addresses a rally in Sivakasi
1996 General Elections - HD Deve Gowda addresses a rally in Pilibhit, Uttar Pradesh
1984 Elections - When Congress played 'anti-national' card
1998 General Elections - Congress Rally in Calicut in Kerala
1998 General Elections - Congress rally in Punjab
1998 General Elections - Indra Kumar Gujral's rally in Punjab
1982 - Then PM Indira Gandhi promises Garibi Hatao
1999 Elections - Atal Bihari Vajpayee's rally after beating Pakistan in Kargil War
1991 General Elections - Chandra Shekhar addresses public meeting in Delhi
1983 Assam Assembly Polls - Indira Gandhi talks about vote bank politics
1984 General Elections - When Rajiv Gandhi promised Nyay
1996 General Elections - HD Deve Gowda addresses a rally in Raebareli
Atal Bihari Vajpayee speech at Amritsar karyakarta sammelan
Amethi in 1984 - Rajiv Gandhi election rally
1984 Elections - Rajiv Gandhi questions ideology of then Opposition Alliance
1967 Election Rally - Indira Gandhi speaks on Gau Hatya
2003 Rajasthan Elections - Atal Bihari Vajpayee addresses a rally in Jaipur
1982 Andhra Elections - Then PM Indira Gandhi promises to eradicate poverty
1984 Elections - Rajiv Gandhi alleges Opposition trying to disintegrate India
1984 Elections - Rajiv Gandhi on Scheme benefits not reaching people
1982 Elections - Indira Gandhi alleges Opposition trying to weaken India
2003 Rajasthan Polls - Atal Bihari Vajpayee addresses a rally in Jodhpur
2003 Rajasthan Polls - Atal Bihari Vajpayee addresses a rally in Ajmer
1983 - Indira Gandhi talks about defeat in post-Emergency Polls
1984 Polls - Rajiv Gandhi on foreign interference in Indian politics
1984 Polls - Rajiv Gandhi talks about Unity
1977 Elections - Indira Gandhi on Emergency
1982 Polls - Indira Gandhi in Hyderabad
Indira Gandhi in 1982 defends Emergency era decries khichdi sarkaar
1984 Elections - Rajiv Gandhi in Dehradun talks of "Bharat ke Tukde Tukde" Politics
1984 Polls - When Congress promised New India
1984 Elections - Rajiv Gandhi questions Opposition's agenda
1984 Polls - Rajiv Gandhi alleges Opposition supporting Tukde Tukde gang
Rajeev Gandhi Election Meeting, Thanjavur 1984
Indira Gandhi Public Meeting Election Speech, Ramanagara Karnataka 1982
Rajeev Gandhi Election Meeting  Marina Beach, Madras  1984
Rajeev Gandhi Election Meeting  Valsad Gujarat 1984
1982 Elections - Congress rally in Bengaluru
1982 Elections - Indira Gandhi calls for stable government
1982 Elections - When Indira Gandhi promised Garibi Hatao
1989 Elections - When Rajiv Gandhi promised 'Vikas'
1989 Elections - Rajiv Gandhi slams Pakistan for abetting terrorism in India
1989 Elections - Rajiv Gandhi on Babri Masjid-Ram Mandir dispute
1989 Elections - Rajiv Gandhi on importance of secrecy of military operations
1998 Rajasthan Assembly Elections - Atal Bihari Vajpayee's rally in Kota
Indira Gandhi on why she was expelled from the Parliament
1996 - Atal Bihari Vajpayee's speech on General Elections results
1977 - Atal Bihari Vajpayee on Emergence of Janata Party
1977 - Atal Bihari Vajpayee address the nation..."राष्ट्रीय जाग्रयम् वयम्"
[Private video]

WARNING: [youtube:tab] YouTube said: INFO - 2 unavailable videos are hidden

1989 - Then PM Rajiv Gandhi's independence day speech
1987 - Then PM Rajiv Gandhi's Independence Day Speech
1985 - Then PM Rajiv Gandhi's Independence Day speech | Call for National “Harmony”
1989 Elections - When Rajiv Gandhi promised 'Vikas'
1989 Elections - Rajiv Gandhi on importance of secrecy of military operations
1989 Elections - Rajiv Gandhi slams Pakistan for abetting terrorism in India
1989 Elections - Rajiv Gandhi on Babri Masjid-Ram Mandir dispute
1984 Elections - Rajiv Gandhi questions Opposition's agenda
1984 Polls - Rajiv Gandhi alleges Opposition supporting Tukde Tukde gang
1984 Elections - Rajiv Gandhi in Dehradun talks of "Bharat ke Tukde Tukde" Politics
1984 Polls - Rajiv Gandhi talks about Unity
1984 Polls - Rajiv Gandhi on foreign interference in Indian politics
1984 Elections - Rajiv Gandhi on Scheme benefits not reaching people
1984 Elections - Rajiv Gandhi alleges Opposition trying to disintegrate India
1984 Elections - Rajiv Gandhi questions ideology of then Opposition Alliance
Amethi in 1984 - Rajiv Gandhi election rally
1984 General Elections - When Rajiv Gandhi promised Nyay
Rajiv Gandhi talks about Army's action in Punjab in 1984 Election rally
After Bhopal Gas Tragedy, Rajiv Gandhi's election rally in Bengaluru
Rajiv Gandhi's election rally a day after Bhopal Gas Tragedy
1986 - Then PM Rajiv Gandhi's Independence Day Speech
1988 - Then PM Rajiv Gandhi's Independence Day Speech
1986 - Then PM Rajiv Gandhi & Gen. Sec. Mikhail Gorbachev in Joint Press Conference
Former PM Rajiv Gandhi - A Documentary
[Private video]
[Private video]
1998- Election Broadcast by Pranab Mukherjee
1994 - Interview with Former President Sh. Pranab Mukherjee
2016 - Former President Sh. Pranab Mukherjee's speech in Gwalior
2016- Former President Sh. Pranab Mukherjee on life & livelihood
2017- Former President Sh. Pranab Mukherjee on Buddhism
Excerpts from the Interview with former President of India, Shri Pranab Mukherjee
Tribute to the former President of India, Shri Pranab Mukherjee
2013 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2015 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
2016 - Pranab Mukherjee's Message to the Nation | Eve of Independence Day
1999 - K. R. Narayanan' s Message to the Nation | Eve of Independence Day
2002 - Then President K. R. Narayanan Addressing the Budget Session
2001 - Then President K. R. Narayanan Addressing the Budget Session
1998 - K.R. Narayan Message To The Nation | President's speech on  Eve of Republic Day

In [ ]:
dataset = pd.concat(dfs)
dataset.drop_duplicates(inplace = True)
dataset = dataset[~dataset.text.str.contains('No Transcript Available')]

In [ ]:
len(dataset)

0

In [ ]:
dataset['text'] = dataset['text'].str.replace('praise','').str.replace('Praise','').str.replace('Music','').str.replace('music','').str.replace('applause','').str.replace('Applause','').str.replace('laughter','').str.replace('Laughter','').str.replace('[','').str.replace(']','')
dataset["words"] = dataset["text"].apply(lambda n: len(n.split()))

In [ ]:
modi_speech = pd.read_csv('PM_Modi_speeches.csv')
modi_speech_en = modi_speech[modi_speech.lang == 'en'][['url','title','text','words']]
dataset = pd.concat([dataset, modi_speech_en])

In [ ]:
len(dataset)

491

In [ ]:
dataset.head()

,url,title,text,words
0,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address in the 15th Episode of ‘Mann Ki B...,"My dear countrymen, Namaskar.\nGenerally, this...",21619
1,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address at inauguration of the College an...,Our country’s Agriculture Minister Shri Narend...,10128
2,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address at seminar on Atmanirbhar Bharat ...,"My cabinet colleague, Shri Rajnath ji, Chief o...",8497
3,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address to the Nation from the ramparts o...,"My dear countrymen,\nCongratulations and many ...",50260
4,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address at the Launch of ‘Transparent Tax...,The process of Structural Reforms going on in ...,11908

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab') # Required for newer versions of NLTK
from nltk.util import bigrams, trigrams
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
import nltk
from nltk.util import bigrams, trigrams
from nltk.tokenize import word_tokenize

# Function to generate bigrams
def generate_bigrams(text):
    tokens = word_tokenize(text)
    return list(bigrams(tokens))

# Function to generate trigrams
def generate_trigrams(text):
    tokens = word_tokenize(text)
    return list(trigrams(tokens))

# Apply functions to the DataFrame
dataset['bigrams'] = dataset['text'].apply(generate_bigrams)
dataset['trigrams'] = dataset['text'].apply(generate_trigrams)

dataset.head()

,url,title,text,words,bigrams,trigrams
0,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address in the 15th Episode of ‘Mann Ki B...,"My dear countrymen, Namaskar.\nGenerally, this...",21619,"[(My, dear), (dear, countrymen), (countrymen, ...","[(My, dear, countrymen), (dear, countrymen, ,)..."
1,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address at inauguration of the College an...,Our country’s Agriculture Minister Shri Narend...,10128,"[(Our, country), (country, ’), (’, s), (s, Agr...","[(Our, country, ’), (country, ’, s), (’, s, Ag..."
2,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address at seminar on Atmanirbhar Bharat ...,"My cabinet colleague, Shri Rajnath ji, Chief o...",8497,"[(My, cabinet), (cabinet, colleague), (colleag...","[(My, cabinet, colleague), (cabinet, colleague..."
3,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address to the Nation from the ramparts o...,"My dear countrymen,\nCongratulations and many ...",50260,"[(My, dear), (dear, countrymen), (countrymen, ...","[(My, dear, countrymen), (dear, countrymen, ,)..."
4,https://www.pmindia.gov.in/en/news_updates/pms...,PM’s address at the Launch of ‘Transparent Tax...,The process of Structural Reforms going on in ...,11908,"[(The, process), (process, of), (of, Structura...","[(The, process, of), (process, of, Structural)..."

In [ ]:
dataset.to_csv('political_speech_dataset.csv')

In [ ]:
import pandas as pd
dataset = pd.read_csv('political_speech_dataset.csv')

Mounted at /content/drive

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.
WARNING:huggingface_hub._login:Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (5.9.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.29.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.11.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.24.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=1.3.0->transformers) (0.1.2)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

KeyboardInterrupt: